Automated template update to v0.5.0

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,45 +1,59 @@
 name: Test
 
 on:
-  workflow_call:
+  push:
+    branches: [main]
+  pull_request:
+    branches: [main]
+  schedule:
+    - cron: "0 5 1,15 * *"
 
-permissions:
-  contents: read # to fetch code (actions/checkout)
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
+defaults:
+  run:
+    # to fail on error in multiline statements (-e), in pipes (-o pipefail), and on unset variables (-u).
+    shell: bash -euo pipefail {0}
+
 jobs:
   test:
-    name: ${{ matrix.os }} - ${{ matrix.python-version }}
     runs-on: ${{ matrix.os }}
+
     strategy:
-      # Ensure that if any job fails, all jobs are cancelled.
       fail-fast: false
       matrix:
-        python-version: ["3.9", "3.10", "3.11", "3.12"]
-        os: [ubuntu-latest, macos-latest, windows-latest]
+        include:
+          - os: ubuntu-latest
+            python: "3.10"
+          - os: ubuntu-latest
+            python: "3.12"
+          - os: ubuntu-latest
+            python: "3.12"
+            pip-flags: "--pre"
+            name: PRE-RELEASE DEPENDENCIES
+
+    name: ${{ matrix.name }} Python ${{ matrix.python }}
+
+    env:
+      OS: ${{ matrix.os }}
+      PYTHON: ${{ matrix.python }}
 
     steps:
-      - name: Checkout ${{ github.repository }}
-        uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
+          filter: blob:none
           fetch-depth: 0
-
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v4
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
         with:
-          python-version: ${{ matrix.python-version }}
-          cache-dependency-path: "**/pyproject.toml"
-          cache: "pip"
-
-      - name: Install Dependencies and ${{ github.repository }}
-        run: |
-          pip install .[test]
-
-      - name: Run Tests
-        run: |
-          pytest
-
-      - name: Archive Coverage
-        uses: actions/upload-artifact@v4
-        with:
-          name: coverage-${{ join(matrix.*, '-') }}
-          path: |
-            coverage.lcov
+          cache-dependency-glob: pyproject.toml
+      - name: run tests using hatch
+        env:
+          MPLBACKEND: agg
+          PLATFORM: ${{ matrix.os }}
+          DISPLAY: :42
+        run: uvx hatch test --cover --python ${{ matrix.python }}
+      - name: Upload coverage
+        uses: codecov/codecov-action@v4
